### ISSUE TITLE
Is this available for public use? 

### ISSUE THREAD

**Issue by netzih** [MegaphoneJon/ansible-role-deploy-site#1]
I've been looking for a similar idea for civicrm and came across this.
Is there a simple tutorial on how to deploy a site using this?
Thanks.

**Comment by MegaphoneJon** [comment]
@netzih  You're right that I should explicitly license these - but for now,  this is my public declaration that any of my repos beginning with `ansible-role` are MIT licensed if it's not a fork of someone else's repo. 

My `ansible-main` repo contains this and all the other roles as submodules. I can talk about it on chat and help you get into it.  My inventory is stored in my Drupal site, and a script in `ansible-main` queries it.

However, the upshot is that this isn't cleaned up for public use and has a lot of Megaphone-isms in it.  I don't recommend trying to use this, but rather to see how I'm doing certain things.

Also - if I were starting today, I would probably make use of Docker and do far less in Ansible.
